# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y1uD29hSjrTQyPEUoO4QvcOLpsT6jp_K
"""

#DEFINIR VARIABLE 2.19

radio=float
math :float=3.14

#definir datos de entrada
radio= float(input("escribir la radio: "))


#proseso
longitud =(2*math*radio)
#datos de salida
print(f"la longitud es :{longitud}")

#DIFINIR VARIABLE
from math import sqrt
ab=float
bc=float
#Definir datos de entrada
ab=float(input("escribir la longitud del virtice AB :"))

print("escribir un numero:")
bc=float(input("escrbir la longitud del vertice BC:"))
print("escribir un numero: ")

#procesos
hipotenusa= sqrt(ab**2+bc**2)
#datos de salida 
print(f"la longitud de la hipotenusa es :{hipotenusa}")