# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N6f4l2RjVW3YejJD2MpKB8HvvV2KzgWF
"""

#Definir variables  2.1
base=None 
altura=None
#Datos de entrada 
base=float(input("Escribe la base del triangulo:"))
altura=float(input("Escribe la altura del triangulo:"))
#proceso
area=(base*altura)/2
#Datos de salida 
print(f"El area del triangulo es:{area}")

#Difinir año  2.3
fecha=int
año=int
#Datos de entrada
fecha=int(input("escribir el an:"))
año=int(input("escribir el ac:"))
#proceso
edad=(fecha-año) 
#Datos de salida 
print(f"El año actual:{edad}")