# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JP8NiKn_R9yz-adb5-bm_ctXMzC3dQEt
"""

#Difinir variables    2.4
horas:float
promocion:float
pago:float
#Datos de entrada
pago=float(input("dame las horas consumidas: "))
#proceso
promocion = (pago / 10)
total= (pago - promocion)
#datos de salida
print(f"usted debe pagar {total} soles:")

#Definir variables 
m2=float
cm2=float=2
presupuesto=float
#Datos de entrada
m2=int(input("cuantos metros2 desee que se pinte: "))
#proceso
presupuesto= m2/cm2
#Datos de salida
print(f"el presupuesto del trabajo sera:,{presupuesto} ")